version: '3.1'

services:

  web:
    container_name: yii2_web
    build: ./docker/web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${WEB_ROOT_PATH}:/var/www/html/
#      - ./secrets:/secrets/
    ports:
      - ${WEB_PORT}:80
    working_dir: ${WEB_WORKING_DIR}

  mysql:
    container_name: yii2_mysql
    image: mysql:5.7
    restart: ${MYSQL_RESTART}
    command: --init-file /data/application/init.sql
    volumes:
      - ./docker/mysql/init.sql:/data/application/init.sql
      - ${MYSQL_PATH}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
    ports:
      - ${PHPMYADMIN_PORT}:80

  composer:
    image: composer:1.6
    volumes:
      - ${WEB_ROOT_PATH}:/var/www/html/
    working_dir: ${WEB_WORKING_DIR}
    command: composer update --ignore-platform-reqs

#networks:
#  default:
#    external:
#      name: user_bridge